### ISSUE TITLE
本地搭建出错

### ISSUE THREAD

**Issue by shacai** [MinskyNg/react-chat#1]
本地搭建聊天室的时候出错 如图
![qq 20170317121336](https://cloud.githubusercontent.com/assets/11889610/24028598/505e5f5c-0b0b-11e7-9271-65f36dd35fd7.jpg)
打开localhost 网页显示Not found
求大神解答 感激

**Comment by MinskyNg** [comment]
这个问题我也没遇过啊。。。
[你可以看看这个能不能解决](http://stackoverflow.com/questions/37162151/gulp-webpack-error-entry-module-not-found-error-cannot-resolve-module-babel)

**Comment by shacai** [comment]
博主你可以发一份你本地能运行的项目代码给我吗邮箱wzj@iwonz.cn 我弄了半天还是不行
菜鸟学习中...
